# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Assignment' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'Kingfisher', '~> 5.0'

  target 'AssignmentTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'AssignmentUITests' do
    # Pods for testing
  end

end
